import type {
  Country,
  Cuisine,
  Ingredient,
  Recipe,
  Region,
} from '@emrooz/types';

/**
 * Bundled demo dataset. Deliberately globally varied — spans Europe, Asia,
 * Americas, Africa, and the Middle East so a developer running the app fresh
 * immediately sees a global experience (per CLAUDE.md §47). Afghan cuisine is
 * present as one of many cuisines, not the majority.
 *
 * All content here is either originally written for Emrooz or clearly synthetic
 * test content. It is safe to distribute with the source tree.
 */

const now = '2026-09-03T00:00:00.000Z';

const emroozProvenance = {
  contentOwner: 'Emrooz',
  ownershipType: 'emrooz_owned' as const,
  storagePermission: 'permanent' as const,
};

export const COUNTRIES: Country[] = [
  { id: 'c_af', code: 'AF', name: { en: 'Afghanistan' } },
  { id: 'c_it', code: 'IT', name: { en: 'Italy' } },
  { id: 'c_jp', code: 'JP', name: { en: 'Japan' } },
  { id: 'c_mx', code: 'MX', name: { en: 'Mexico' } },
  { id: 'c_in', code: 'IN', name: { en: 'India' } },
  { id: 'c_tr', code: 'TR', name: { en: 'Türkiye' } },
  { id: 'c_vn', code: 'VN', name: { en: 'Vietnam' } },
  { id: 'c_fr', code: 'FR', name: { en: 'France' } },
  { id: 'c_et', code: 'ET', name: { en: 'Ethiopia' } },
  { id: 'c_de', code: 'DE', name: { en: 'Germany' } },
  { id: 'c_th', code: 'TH', name: { en: 'Thailand' } },
  { id: 'c_kr', code: 'KR', name: { en: 'South Korea' } },
  { id: 'c_br', code: 'BR', name: { en: 'Brazil' } },
  { id: 'c_gr', code: 'GR', name: { en: 'Greece' } },
  { id: 'c_ir', code: 'IR', name: { en: 'Iran' } },
  { id: 'c_ma', code: 'MA', name: { en: 'Morocco' } },
];

export const REGIONS: Region[] = [
  { id: 'r_kabul', countryId: 'c_af', name: { en: 'Kabul' } },
  { id: 'r_herat', countryId: 'c_af', name: { en: 'Herat' } },
  { id: 'r_naples', countryId: 'c_it', name: { en: 'Naples' } },
  { id: 'r_tokyo', countryId: 'c_jp', name: { en: 'Tokyo' } },
  { id: 'r_puebla', countryId: 'c_mx', name: { en: 'Puebla' } },
];

export const CUISINES: Cuisine[] = [
  { id: 'cu_afghan', slug: 'afghan', name: { en: 'Afghan' }, primaryCountryId: 'c_af' },
  { id: 'cu_italian', slug: 'italian', name: { en: 'Italian' }, primaryCountryId: 'c_it' },
  { id: 'cu_japanese', slug: 'japanese', name: { en: 'Japanese' }, primaryCountryId: 'c_jp' },
  { id: 'cu_mexican', slug: 'mexican', name: { en: 'Mexican' }, primaryCountryId: 'c_mx' },
  { id: 'cu_indian', slug: 'indian', name: { en: 'Indian' }, primaryCountryId: 'c_in' },
  { id: 'cu_turkish', slug: 'turkish', name: { en: 'Turkish' }, primaryCountryId: 'c_tr' },
  { id: 'cu_vietnamese', slug: 'vietnamese', name: { en: 'Vietnamese' }, primaryCountryId: 'c_vn' },
  { id: 'cu_french', slug: 'french', name: { en: 'French' }, primaryCountryId: 'c_fr' },
  { id: 'cu_ethiopian', slug: 'ethiopian', name: { en: 'Ethiopian' }, primaryCountryId: 'c_et' },
  { id: 'cu_german', slug: 'german', name: { en: 'German' }, primaryCountryId: 'c_de' },
  { id: 'cu_thai', slug: 'thai', name: { en: 'Thai' }, primaryCountryId: 'c_th' },
  { id: 'cu_korean', slug: 'korean', name: { en: 'Korean' }, primaryCountryId: 'c_kr' },
  { id: 'cu_brazilian', slug: 'brazilian', name: { en: 'Brazilian' }, primaryCountryId: 'c_br' },
  { id: 'cu_greek', slug: 'greek', name: { en: 'Greek' }, primaryCountryId: 'c_gr' },
  { id: 'cu_iranian', slug: 'iranian', name: { en: 'Iranian' }, primaryCountryId: 'c_ir' },
  { id: 'cu_moroccan', slug: 'moroccan', name: { en: 'Moroccan' }, primaryCountryId: 'c_ma' },
];

function ing(
  id: string,
  english: string,
  opts: Partial<Ingredient> = {},
  aliases?: string[],
): Ingredient {
  return {
    id,
    slug: id.replace(/_/g, '-'),
    name: { en: english },
    aliases: { en: aliases ?? [] },
    category: opts.category ?? 'other',
    commonUnits: opts.commonUnits ?? [],
    allergens: opts.allergens ?? [],
    dietaryCompatibility: opts.dietaryCompatibility ?? {},
  };
}

const OMNI_VEG = {
  vegetarian: 'compatible',
  vegan: 'compatible',
  halal: 'compatible',
  kosher: 'compatible',
  pescatarian: 'compatible',
} as const;

export const INGREDIENTS: Ingredient[] = [
  // Grains & staples
  ing('rice', 'Rice', { category: 'grain', commonUnits: ['g', 'cup'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('basmati_rice', 'Basmati rice', { category: 'grain', commonUnits: ['g', 'cup'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }, ['long-grain rice']),
  ing('flour', 'All-purpose flour', { category: 'grain', commonUnits: ['g', 'cup'], allergens: ['gluten', 'wheat'], dietaryCompatibility: { ...OMNI_VEG, dairy_free: 'compatible', gluten_free: 'incompatible' } }, ['plain flour', 'wheat flour']),
  ing('bread', 'Bread', { category: 'grain', commonUnits: ['slice', 'piece'], allergens: ['gluten', 'wheat'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'incompatible' } }),
  ing('pasta', 'Pasta', { category: 'grain', commonUnits: ['g'], allergens: ['gluten', 'wheat'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'incompatible' } }),
  ing('bulgur', 'Bulgur', { category: 'grain', commonUnits: ['g'], allergens: ['gluten', 'wheat'], dietaryCompatibility: { ...OMNI_VEG } }),
  ing('rice_paper', 'Rice paper', { category: 'grain', commonUnits: ['piece'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible' } }),

  // Vegetables
  ing('onion', 'Onion', { category: 'vegetable', commonUnits: ['piece', 'g'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('tomato', 'Tomato', { category: 'vegetable', commonUnits: ['piece', 'g'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('eggplant', 'Eggplant', { category: 'vegetable', commonUnits: ['piece'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }, ['aubergine', 'brinjal', 'baingan']),
  ing('zucchini', 'Zucchini', { category: 'vegetable', commonUnits: ['piece'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }, ['courgette']),
  ing('spinach', 'Spinach', { category: 'vegetable', commonUnits: ['g'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('bell_pepper', 'Bell pepper', { category: 'vegetable', commonUnits: ['piece'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }, ['capsicum']),
  ing('carrot', 'Carrot', { category: 'vegetable', commonUnits: ['piece'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('potato', 'Potato', { category: 'vegetable', commonUnits: ['piece'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('cabbage', 'Cabbage', { category: 'vegetable', commonUnits: ['g'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('mushroom', 'Mushroom', { category: 'vegetable', commonUnits: ['g'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('lettuce', 'Lettuce', { category: 'vegetable', commonUnits: ['piece'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('garlic', 'Garlic', { category: 'vegetable', commonUnits: ['clove'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('ginger', 'Ginger', { category: 'vegetable', commonUnits: ['g'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('scallion', 'Scallion', { category: 'vegetable', commonUnits: ['piece'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }, ['green onion', 'spring onion']),
  ing('cilantro', 'Cilantro', { category: 'herb', commonUnits: ['g'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }, ['coriander leaves', 'fresh coriander']),
  ing('parsley', 'Parsley', { category: 'herb', commonUnits: ['g'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('basil', 'Basil', { category: 'herb', commonUnits: ['g'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('mint', 'Mint', { category: 'herb', commonUnits: ['g'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('dill', 'Dill', { category: 'herb', commonUnits: ['g'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),

  // Legumes
  ing('chickpea', 'Chickpeas', { category: 'legume', commonUnits: ['g', 'cup'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible', high_protein: 'compatible' } }, ['garbanzo bean', 'garbanzo beans']),
  ing('lentil_red', 'Red lentils', { category: 'legume', commonUnits: ['g'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible', high_protein: 'compatible' } }),
  ing('lentil_green', 'Green lentils', { category: 'legume', commonUnits: ['g'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible', high_protein: 'compatible' } }),
  ing('black_bean', 'Black beans', { category: 'legume', commonUnits: ['g'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible', high_protein: 'compatible' } }),
  ing('kidney_bean', 'Kidney beans', { category: 'legume', commonUnits: ['g'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),

  // Meats & fish
  ing('chicken', 'Chicken', {
    category: 'poultry',
    commonUnits: ['g'],
    dietaryCompatibility: { vegetarian: 'incompatible', vegan: 'incompatible', pescatarian: 'incompatible', halal: 'compatible', kosher: 'compatible', dairy_free: 'compatible', gluten_free: 'compatible', high_protein: 'compatible' },
  }),
  ing('lamb', 'Lamb', {
    category: 'meat',
    commonUnits: ['g'],
    dietaryCompatibility: { vegetarian: 'incompatible', vegan: 'incompatible', pescatarian: 'incompatible', halal: 'compatible', kosher: 'compatible', dairy_free: 'compatible', gluten_free: 'compatible', high_protein: 'compatible' },
  }),
  ing('beef', 'Beef', {
    category: 'meat',
    commonUnits: ['g'],
    dietaryCompatibility: { vegetarian: 'incompatible', vegan: 'incompatible', pescatarian: 'incompatible', halal: 'compatible', kosher: 'compatible', dairy_free: 'compatible', gluten_free: 'compatible', high_protein: 'compatible' },
  }),
  ing('pork', 'Pork', {
    category: 'meat',
    commonUnits: ['g'],
    dietaryCompatibility: { vegetarian: 'incompatible', vegan: 'incompatible', pescatarian: 'incompatible', halal: 'incompatible', kosher: 'incompatible', dairy_free: 'compatible', gluten_free: 'compatible', high_protein: 'compatible' },
  }),
  ing('shrimp', 'Shrimp', {
    category: 'seafood',
    commonUnits: ['g'],
    allergens: ['shellfish'],
    dietaryCompatibility: { vegetarian: 'incompatible', vegan: 'incompatible', pescatarian: 'compatible', halal: 'compatible', kosher: 'incompatible', dairy_free: 'compatible', gluten_free: 'compatible' },
  }, ['prawns']),
  ing('salmon', 'Salmon', {
    category: 'seafood',
    commonUnits: ['g'],
    allergens: ['fish'],
    dietaryCompatibility: { vegetarian: 'incompatible', vegan: 'incompatible', pescatarian: 'compatible', halal: 'compatible', kosher: 'compatible', dairy_free: 'compatible', gluten_free: 'compatible', high_protein: 'compatible' },
  }),
  ing('tuna', 'Tuna', {
    category: 'seafood',
    commonUnits: ['g'],
    allergens: ['fish'],
    dietaryCompatibility: { vegetarian: 'incompatible', vegan: 'incompatible', pescatarian: 'compatible', halal: 'compatible', kosher: 'compatible', dairy_free: 'compatible', gluten_free: 'compatible', high_protein: 'compatible' },
  }),
  ing('tofu', 'Tofu', {
    category: 'other',
    commonUnits: ['g'],
    allergens: ['soy'],
    dietaryCompatibility: { ...OMNI_VEG, dairy_free: 'compatible', gluten_free: 'compatible', high_protein: 'compatible' },
  }),

  // Dairy & eggs
  ing('milk', 'Milk', { category: 'dairy', commonUnits: ['ml'], allergens: ['dairy'], dietaryCompatibility: { vegetarian: 'compatible', vegan: 'incompatible', halal: 'compatible', gluten_free: 'compatible', dairy_free: 'incompatible' } }),
  ing('yogurt', 'Yogurt', { category: 'dairy', commonUnits: ['g'], allergens: ['dairy'], dietaryCompatibility: { vegetarian: 'compatible', vegan: 'incompatible', halal: 'compatible', gluten_free: 'compatible', dairy_free: 'incompatible' } }),
  ing('butter', 'Butter', { category: 'dairy', commonUnits: ['g'], allergens: ['dairy'], dietaryCompatibility: { vegetarian: 'compatible', vegan: 'incompatible', halal: 'compatible', gluten_free: 'compatible', dairy_free: 'incompatible' } }),
  ing('cheese_mozz', 'Mozzarella', { category: 'dairy', commonUnits: ['g'], allergens: ['dairy'], dietaryCompatibility: { vegetarian: 'compatible', vegan: 'incompatible', halal: 'compatible', gluten_free: 'compatible', dairy_free: 'incompatible' } }),
  ing('cheese_feta', 'Feta', { category: 'dairy', commonUnits: ['g'], allergens: ['dairy'], dietaryCompatibility: { vegetarian: 'compatible', vegan: 'incompatible', halal: 'compatible', gluten_free: 'compatible', dairy_free: 'incompatible' } }),
  ing('parmesan', 'Parmesan', { category: 'dairy', commonUnits: ['g'], allergens: ['dairy'], dietaryCompatibility: { vegetarian: 'compatible', vegan: 'incompatible', halal: 'compatible', gluten_free: 'compatible', dairy_free: 'incompatible' } }),
  ing('egg', 'Egg', { category: 'egg', commonUnits: ['piece'], allergens: ['egg'], dietaryCompatibility: { vegetarian: 'compatible', vegan: 'incompatible', halal: 'compatible', kosher: 'compatible', gluten_free: 'compatible', dairy_free: 'compatible', egg_free: 'incompatible' } }),

  // Fats and condiments
  ing('olive_oil', 'Olive oil', { category: 'fat_or_oil', commonUnits: ['tbsp', 'ml'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('vegetable_oil', 'Vegetable oil', { category: 'fat_or_oil', commonUnits: ['tbsp'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('soy_sauce', 'Soy sauce', { category: 'condiment', commonUnits: ['tbsp'], allergens: ['soy'], dietaryCompatibility: { ...OMNI_VEG, dairy_free: 'compatible' } }),
  ing('fish_sauce', 'Fish sauce', { category: 'condiment', commonUnits: ['tbsp'], allergens: ['fish'], dietaryCompatibility: { vegetarian: 'incompatible', vegan: 'incompatible', pescatarian: 'compatible', halal: 'compatible', dairy_free: 'compatible' } }),
  ing('vinegar', 'Vinegar', { category: 'condiment', commonUnits: ['tbsp'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('lemon', 'Lemon', { category: 'fruit', commonUnits: ['piece'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('lime', 'Lime', { category: 'fruit', commonUnits: ['piece'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),

  // Spices
  ing('salt', 'Salt', { category: 'spice', commonUnits: ['tsp'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('pepper', 'Black pepper', { category: 'spice', commonUnits: ['tsp'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('cumin', 'Cumin', { category: 'spice', commonUnits: ['tsp'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('coriander_seed', 'Coriander seed', { category: 'spice', commonUnits: ['tsp'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('turmeric', 'Turmeric', { category: 'spice', commonUnits: ['tsp'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('cardamom', 'Cardamom', { category: 'spice', commonUnits: ['piece'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('cinnamon', 'Cinnamon', { category: 'spice', commonUnits: ['tsp'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('chili_powder', 'Chili powder', { category: 'spice', commonUnits: ['tsp'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('paprika', 'Paprika', { category: 'spice', commonUnits: ['tsp'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('berbere', 'Berbere', { category: 'spice', commonUnits: ['tsp'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),

  // Nuts and seeds
  ing('walnut', 'Walnuts', { category: 'nut_or_seed', commonUnits: ['g'], allergens: ['tree_nut'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible', nut_free: 'incompatible' } }),
  ing('almond', 'Almonds', { category: 'nut_or_seed', commonUnits: ['g'], allergens: ['tree_nut'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible', nut_free: 'incompatible' } }),
  ing('peanut', 'Peanuts', { category: 'nut_or_seed', commonUnits: ['g'], allergens: ['peanut'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible', nut_free: 'incompatible' } }),
  ing('sesame', 'Sesame', { category: 'nut_or_seed', commonUnits: ['tbsp'], allergens: ['sesame'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),

  // Sweeteners
  ing('sugar', 'Sugar', { category: 'sweetener', commonUnits: ['tsp', 'g'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('honey', 'Honey', { category: 'sweetener', commonUnits: ['tbsp'], dietaryCompatibility: { vegetarian: 'compatible', vegan: 'incompatible', halal: 'compatible', gluten_free: 'compatible', dairy_free: 'compatible' } }),

  // Extras used in specific recipes
  ing('coconut_milk', 'Coconut milk', { category: 'other', commonUnits: ['ml'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible', nut_free: 'compatible' } }),
  ing('miso', 'Miso paste', { category: 'condiment', commonUnits: ['tbsp'], allergens: ['soy'], dietaryCompatibility: { ...OMNI_VEG, dairy_free: 'compatible' } }),
  ing('nori', 'Nori', { category: 'other', commonUnits: ['piece'], dietaryCompatibility: { ...OMNI_VEG, pescatarian: 'compatible', gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('tortilla', 'Tortilla', { category: 'grain', commonUnits: ['piece'], allergens: ['gluten', 'wheat'], dietaryCompatibility: { ...OMNI_VEG, dairy_free: 'compatible' } }),
  ing('corn_tortilla', 'Corn tortilla', { category: 'grain', commonUnits: ['piece'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('gochujang', 'Gochujang', { category: 'condiment', commonUnits: ['tbsp'], allergens: ['soy'], dietaryCompatibility: { ...OMNI_VEG, dairy_free: 'compatible' } }),
  ing('injera_flour', 'Teff flour', { category: 'grain', commonUnits: ['g'], dietaryCompatibility: { ...OMNI_VEG, gluten_free: 'compatible', dairy_free: 'compatible' } }),
  ing('couscous', 'Couscous', { category: 'grain', commonUnits: ['g'], allergens: ['gluten', 'wheat'], dietaryCompatibility: { ...OMNI_VEG, dairy_free: 'compatible', gluten_free: 'incompatible' } }),
];

function recipe(
  id: string,
  title: string,
  patch: Partial<Recipe> & Pick<Recipe, 'ingredients' | 'steps' | 'cuisineIds'>,
): Recipe {
  return {
    id,
    slug: id.replace(/_/g, '-'),
    title: { en: title },
    cuisineIds: patch.cuisineIds,
    regionIds: patch.regionIds ?? [],
    prepMinutes: patch.prepMinutes ?? 15,
    cookMinutes: patch.cookMinutes ?? 25,
    totalMinutes: patch.totalMinutes ?? (patch.prepMinutes ?? 15) + (patch.cookMinutes ?? 25),
    difficulty: patch.difficulty ?? 'easy',
    mealTypes: patch.mealTypes ?? ['dinner'],
    servings: patch.servings ?? 4,
    ingredients: patch.ingredients,
    steps: patch.steps,
    dietaryTags: patch.dietaryTags ?? [],
    allergens: patch.allergens ?? [],
    images: patch.images ?? [],
    provenance: patch.provenance ?? emroozProvenance,
    editorialState: patch.editorialState ?? 'published',
    authenticityReview: patch.authenticityReview ?? 'unreviewed',
    publishedAt: patch.publishedAt ?? now,
    updatedAt: now,
    createdAt: now,
    version: 1,
    alternativeNames: patch.alternativeNames,
    description: patch.description,
    originCountryId: patch.originCountryId,
  };
}

const R = (n: number, text: string) => ({ order: n, text: { en: text } });

export const RECIPES: Recipe[] = [
  recipe('qabuli_palaw', 'Qabuli Palaw', {
    cuisineIds: ['cu_afghan'],
    originCountryId: 'c_af',
    regionIds: ['r_kabul'],
    alternativeNames: { en: ['Kabuli Pulao', 'Qabili Palaw'] },
    description: { en: 'Fragrant lamb pilaf with caramelized carrots and raisins — the celebration dish of Afghan tables.' },
    prepMinutes: 25,
    cookMinutes: 75,
    difficulty: 'medium',
    mealTypes: ['dinner', 'lunch'],
    servings: 6,
    dietaryTags: ['halal', 'dairy_free'],
    ingredients: [
      { ingredientId: 'basmati_rice', quantity: 500, unit: 'g' },
      { ingredientId: 'lamb', quantity: 800, unit: 'g' },
      { ingredientId: 'onion', quantity: 2, unit: 'piece' },
      { ingredientId: 'carrot', quantity: 3, unit: 'piece' },
      { ingredientId: 'cardamom', quantity: 4, unit: 'piece' },
      { ingredientId: 'cumin', quantity: 1, unit: 'tsp' },
      { ingredientId: 'vegetable_oil', quantity: 4, unit: 'tbsp' },
      { ingredientId: 'salt', quantity: 2, unit: 'tsp' },
    ],
    steps: [
      R(0, 'Brown the onion in oil, add lamb and sear until deeply colored.'),
      R(1, 'Add spices and enough water to cover, simmer covered until lamb is tender, about 60 minutes.'),
      R(2, 'Meanwhile julienne carrots and sauté with a touch of sugar until glossy.'),
      R(3, 'Parboil the rice, layer with lamb and carrots in the same pot, cover and steam 25 minutes.'),
      R(4, 'Rest 10 minutes off the heat, then mound onto a platter, carrots on top.'),
    ],
  }),
  recipe('bolani_kadu', 'Bolani Kadu', {
    cuisineIds: ['cu_afghan'],
    originCountryId: 'c_af',
    alternativeNames: { en: ['Pumpkin bolani'] },
    prepMinutes: 30,
    cookMinutes: 15,
    difficulty: 'medium',
    mealTypes: ['lunch', 'snack', 'appetizer'],
    servings: 4,
    dietaryTags: ['vegetarian', 'vegan', 'halal'],
    allergens: ['gluten', 'wheat'],
    ingredients: [
      { ingredientId: 'flour', quantity: 300, unit: 'g' },
      { ingredientId: 'onion', quantity: 1, unit: 'piece' },
      { ingredientId: 'cumin', quantity: 1, unit: 'tsp' },
      { ingredientId: 'salt', quantity: 1, unit: 'tsp' },
      { ingredientId: 'vegetable_oil', quantity: 2, unit: 'tbsp' },
    ],
    steps: [
      R(0, 'Make a soft dough with flour, water, and a pinch of salt; rest 20 minutes.'),
      R(1, 'Sauté grated pumpkin (kadu) with onion, cumin, and salt until soft.'),
      R(2, 'Roll dough thin, spread filling on one half, fold, seal, and pan-fry until crisp.'),
    ],
  }),
  recipe('margherita_pizza', 'Pizza Margherita', {
    cuisineIds: ['cu_italian'],
    originCountryId: 'c_it',
    regionIds: ['r_naples'],
    prepMinutes: 20,
    cookMinutes: 12,
    difficulty: 'easy',
    mealTypes: ['dinner'],
    servings: 2,
    dietaryTags: ['vegetarian'],
    allergens: ['gluten', 'wheat', 'dairy'],
    ingredients: [
      { ingredientId: 'flour', quantity: 250, unit: 'g' },
      { ingredientId: 'tomato', quantity: 200, unit: 'g' },
      { ingredientId: 'cheese_mozz', quantity: 200, unit: 'g' },
      { ingredientId: 'basil', quantity: 10, unit: 'g' },
      { ingredientId: 'olive_oil', quantity: 2, unit: 'tbsp' },
      { ingredientId: 'salt', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      R(0, 'Preheat oven as hot as it goes with a stone or heavy tray inside.'),
      R(1, 'Stretch the dough, spread crushed tomatoes, tear mozzarella over top.'),
      R(2, 'Bake until crust is blistered, finish with basil and olive oil.'),
    ],
  }),
  recipe('cacio_e_pepe', 'Cacio e Pepe', {
    cuisineIds: ['cu_italian'],
    originCountryId: 'c_it',
    prepMinutes: 5,
    cookMinutes: 15,
    difficulty: 'medium',
    mealTypes: ['dinner'],
    servings: 2,
    dietaryTags: ['vegetarian'],
    allergens: ['gluten', 'wheat', 'dairy'],
    ingredients: [
      { ingredientId: 'pasta', quantity: 200, unit: 'g' },
      { ingredientId: 'parmesan', quantity: 80, unit: 'g' },
      { ingredientId: 'pepper', quantity: 2, unit: 'tsp' },
      { ingredientId: 'salt', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      R(0, 'Cook pasta in less water than usual; save a mug of starchy water.'),
      R(1, 'Toast cracked pepper in a pan, add a splash of pasta water.'),
      R(2, 'Toss pasta and grated cheese off the heat, loosening with water to a glossy sauce.'),
    ],
  }),
  recipe('miso_soup', 'Miso soup with tofu', {
    cuisineIds: ['cu_japanese'],
    originCountryId: 'c_jp',
    regionIds: ['r_tokyo'],
    prepMinutes: 5,
    cookMinutes: 10,
    difficulty: 'easy',
    mealTypes: ['soup', 'breakfast'],
    servings: 2,
    dietaryTags: ['vegetarian', 'pescatarian', 'dairy_free'],
    allergens: ['soy'],
    ingredients: [
      { ingredientId: 'miso', quantity: 2, unit: 'tbsp' },
      { ingredientId: 'tofu', quantity: 150, unit: 'g' },
      { ingredientId: 'scallion', quantity: 2, unit: 'piece' },
      { ingredientId: 'nori', quantity: 1, unit: 'piece' },
    ],
    steps: [
      R(0, 'Warm 500ml water; do not boil.'),
      R(1, 'Whisk miso into a ladle of the water, stir back into the pot.'),
      R(2, 'Add cubed tofu, torn nori, and sliced scallions; serve.'),
    ],
  }),
  recipe('chicken_teriyaki_bowl', 'Chicken teriyaki bowl', {
    cuisineIds: ['cu_japanese'],
    prepMinutes: 10,
    cookMinutes: 20,
    difficulty: 'easy',
    mealTypes: ['dinner', 'lunch'],
    servings: 2,
    dietaryTags: ['halal', 'dairy_free'],
    allergens: ['soy'],
    ingredients: [
      { ingredientId: 'chicken', quantity: 400, unit: 'g' },
      { ingredientId: 'rice', quantity: 200, unit: 'g' },
      { ingredientId: 'soy_sauce', quantity: 4, unit: 'tbsp' },
      { ingredientId: 'sugar', quantity: 2, unit: 'tbsp' },
      { ingredientId: 'ginger', quantity: 10, unit: 'g' },
      { ingredientId: 'scallion', quantity: 2, unit: 'piece' },
    ],
    steps: [
      R(0, 'Sear chicken thighs skin-side down until crisp.'),
      R(1, 'Add soy, sugar, and ginger; reduce until glossy.'),
      R(2, 'Slice and serve over steamed rice with scallions.'),
    ],
  }),
  recipe('tacos_al_pastor_light', 'Weeknight pastor-style tacos', {
    cuisineIds: ['cu_mexican'],
    originCountryId: 'c_mx',
    regionIds: ['r_puebla'],
    prepMinutes: 15,
    cookMinutes: 25,
    difficulty: 'easy',
    mealTypes: ['dinner'],
    servings: 4,
    dietaryTags: ['halal', 'dairy_free'],
    ingredients: [
      { ingredientId: 'chicken', quantity: 500, unit: 'g' },
      { ingredientId: 'corn_tortilla', quantity: 12, unit: 'piece' },
      { ingredientId: 'onion', quantity: 1, unit: 'piece' },
      { ingredientId: 'cilantro', quantity: 20, unit: 'g' },
      { ingredientId: 'lime', quantity: 2, unit: 'piece' },
      { ingredientId: 'paprika', quantity: 1, unit: 'tsp' },
      { ingredientId: 'chili_powder', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      R(0, 'Rub chicken with paprika, chili, salt; sear and slice.'),
      R(1, 'Warm tortillas on a dry pan.'),
      R(2, 'Fill with chicken, top with onion and cilantro, squeeze lime.'),
    ],
  }),
  recipe('vegetarian_enchiladas', 'Black bean enchiladas', {
    cuisineIds: ['cu_mexican'],
    prepMinutes: 15,
    cookMinutes: 25,
    difficulty: 'easy',
    mealTypes: ['dinner'],
    servings: 4,
    dietaryTags: ['vegetarian', 'halal'],
    allergens: ['dairy'],
    ingredients: [
      { ingredientId: 'corn_tortilla', quantity: 8, unit: 'piece' },
      { ingredientId: 'black_bean', quantity: 300, unit: 'g' },
      { ingredientId: 'tomato', quantity: 400, unit: 'g' },
      { ingredientId: 'onion', quantity: 1, unit: 'piece' },
      { ingredientId: 'cheese_mozz', quantity: 200, unit: 'g' },
      { ingredientId: 'chili_powder', quantity: 2, unit: 'tsp' },
    ],
    steps: [
      R(0, 'Simmer tomato with onion and chili powder into a quick sauce.'),
      R(1, 'Fill tortillas with warm beans, roll, tuck into a baking dish, cover in sauce and cheese.'),
      R(2, 'Bake 20 minutes at 200°C until bubbling.'),
    ],
  }),
  recipe('chana_masala', 'Chana masala', {
    cuisineIds: ['cu_indian'],
    originCountryId: 'c_in',
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    mealTypes: ['dinner', 'lunch'],
    servings: 4,
    dietaryTags: ['vegetarian', 'vegan', 'halal', 'dairy_free'],
    ingredients: [
      { ingredientId: 'chickpea', quantity: 400, unit: 'g' },
      { ingredientId: 'onion', quantity: 1, unit: 'piece' },
      { ingredientId: 'tomato', quantity: 400, unit: 'g' },
      { ingredientId: 'ginger', quantity: 15, unit: 'g' },
      { ingredientId: 'garlic', quantity: 3, unit: 'clove' },
      { ingredientId: 'cumin', quantity: 1, unit: 'tsp' },
      { ingredientId: 'turmeric', quantity: 1, unit: 'tsp' },
      { ingredientId: 'chili_powder', quantity: 1, unit: 'tsp' },
    ],
    steps: [
      R(0, 'Sauté onion, ginger, garlic in oil until soft.'),
      R(1, 'Add spices and tomato, cook until fragrant.'),
      R(2, 'Fold in chickpeas, simmer 15 minutes, mash a few beans to thicken.'),
    ],
  }),
  recipe('dal_tadka', 'Dal Tadka', {
    cuisineIds: ['cu_indian'],
    prepMinutes: 5,
    cookMinutes: 25,
    difficulty: 'easy',
    mealTypes: ['dinner', 'lunch'],
    servings: 4,
    dietaryTags: ['vegetarian', 'vegan', 'halal', 'gluten_free', 'dairy_free'],
    ingredients: [
      { ingredientId: 'lentil_red', quantity: 250, unit: 'g' },
      { ingredientId: 'onion', quantity: 1, unit: 'piece' },
      { ingredientId: 'garlic', quantity: 3, unit: 'clove' },
      { ingredientId: 'turmeric', quantity: 1, unit: 'tsp' },
      { ingredientId: 'cumin', quantity: 1, unit: 'tsp' },
      { ingredientId: 'vegetable_oil', quantity: 2, unit: 'tbsp' },
    ],
    steps: [
      R(0, 'Simmer lentils with turmeric and water until falling apart.'),
      R(1, 'Bloom cumin in oil, add onions and garlic, cook until golden.'),
      R(2, 'Pour tadka over the lentils; stir and serve.'),
    ],
  }),
  recipe('menemen', 'Menemen', {
    cuisineIds: ['cu_turkish'],
    originCountryId: 'c_tr',
    prepMinutes: 5,
    cookMinutes: 15,
    difficulty: 'easy',
    mealTypes: ['breakfast', 'brunch'],
    servings: 2,
    dietaryTags: ['vegetarian', 'halal'],
    allergens: ['egg'],
    ingredients: [
      { ingredientId: 'egg', quantity: 4, unit: 'piece' },
      { ingredientId: 'tomato', quantity: 3, unit: 'piece' },
      { ingredientId: 'bell_pepper', quantity: 1, unit: 'piece' },
      { ingredientId: 'olive_oil', quantity: 2, unit: 'tbsp' },
      { ingredientId: 'paprika', quantity: 0.5, unit: 'tsp' },
    ],
    steps: [
      R(0, 'Soften peppers in olive oil until sweet.'),
      R(1, 'Add tomato and paprika, cook down.'),
      R(2, 'Fold beaten eggs through, stopping while still soft.'),
    ],
  }),
  recipe('lentil_shorba', 'Lentil shorba', {
    cuisineIds: ['cu_turkish', 'cu_afghan'],
    prepMinutes: 5,
    cookMinutes: 25,
    difficulty: 'easy',
    mealTypes: ['soup', 'dinner'],
    servings: 4,
    dietaryTags: ['vegetarian', 'vegan', 'halal', 'dairy_free', 'gluten_free'],
    ingredients: [
      { ingredientId: 'lentil_red', quantity: 250, unit: 'g' },
      { ingredientId: 'onion', quantity: 1, unit: 'piece' },
      { ingredientId: 'carrot', quantity: 1, unit: 'piece' },
      { ingredientId: 'cumin', quantity: 1, unit: 'tsp' },
      { ingredientId: 'lemon', quantity: 1, unit: 'piece' },
    ],
    steps: [
      R(0, 'Sweat onion and carrot, add lentils and cumin.'),
      R(1, 'Add water, simmer until soft, blend smooth.'),
      R(2, 'Finish with lemon.'),
    ],
  }),
  recipe('vietnamese_rice_paper_rolls', 'Fresh rice paper rolls', {
    cuisineIds: ['cu_vietnamese'],
    originCountryId: 'c_vn',
    prepMinutes: 25,
    cookMinutes: 0,
    difficulty: 'easy',
    mealTypes: ['lunch', 'appetizer'],
    servings: 4,
    dietaryTags: ['pescatarian', 'dairy_free', 'gluten_free'],
    allergens: ['shellfish', 'soy'],
    ingredients: [
      { ingredientId: 'rice_paper', quantity: 8, unit: 'piece' },
      { ingredientId: 'shrimp', quantity: 200, unit: 'g' },
      { ingredientId: 'lettuce', quantity: 1, unit: 'piece' },
      { ingredientId: 'mint', quantity: 10, unit: 'g' },
      { ingredientId: 'cilantro', quantity: 10, unit: 'g' },
      { ingredientId: 'soy_sauce', quantity: 3, unit: 'tbsp' },
    ],
    steps: [
      R(0, 'Poach shrimp until pink, halve lengthwise.'),
      R(1, 'Dip rice paper, layer lettuce, herbs, and shrimp, roll tightly.'),
      R(2, 'Serve with soy dip.'),
    ],
  }),
  recipe('pho_ga_light', 'Weeknight pho ga', {
    cuisineIds: ['cu_vietnamese'],
    prepMinutes: 10,
    cookMinutes: 30,
    difficulty: 'medium',
    mealTypes: ['soup', 'dinner'],
    servings: 4,
    dietaryTags: ['halal', 'dairy_free'],
    ingredients: [
      { ingredientId: 'chicken', quantity: 600, unit: 'g' },
      { ingredientId: 'ginger', quantity: 20, unit: 'g' },
      { ingredientId: 'onion', quantity: 1, unit: 'piece' },
      { ingredientId: 'cilantro', quantity: 20, unit: 'g' },
      { ingredientId: 'scallion', quantity: 2, unit: 'piece' },
      { ingredientId: 'fish_sauce', quantity: 2, unit: 'tbsp' },
      { ingredientId: 'lime', quantity: 1, unit: 'piece' },
    ],
    steps: [
      R(0, 'Char ginger and onion, drop into simmering water with chicken.'),
      R(1, 'Poach chicken until just cooked, rest and shred.'),
      R(2, 'Season broth with fish sauce; ladle over noodles, top with chicken, herbs, and lime.'),
    ],
  }),
  recipe('ratatouille', 'Ratatouille', {
    cuisineIds: ['cu_french'],
    originCountryId: 'c_fr',
    prepMinutes: 20,
    cookMinutes: 40,
    difficulty: 'medium',
    mealTypes: ['dinner'],
    servings: 4,
    dietaryTags: ['vegetarian', 'vegan', 'halal', 'gluten_free', 'dairy_free'],
    ingredients: [
      { ingredientId: 'eggplant', quantity: 1, unit: 'piece' },
      { ingredientId: 'zucchini', quantity: 1, unit: 'piece' },
      { ingredientId: 'bell_pepper', quantity: 2, unit: 'piece' },
      { ingredientId: 'tomato', quantity: 500, unit: 'g' },
      { ingredientId: 'onion', quantity: 1, unit: 'piece' },
      { ingredientId: 'garlic', quantity: 3, unit: 'clove' },
      { ingredientId: 'olive_oil', quantity: 4, unit: 'tbsp' },
    ],
    steps: [
      R(0, 'Sear vegetables separately in olive oil.'),
      R(1, 'Combine with tomato-garlic base, simmer until melded.'),
      R(2, 'Adjust seasoning and rest before serving.'),
    ],
  }),
  recipe('misir_wot', 'Misir Wot', {
    cuisineIds: ['cu_ethiopian'],
    originCountryId: 'c_et',
    description: { en: 'Ethiopian red lentil stew with berbere.' },
    prepMinutes: 10,
    cookMinutes: 30,
    difficulty: 'easy',
    mealTypes: ['dinner'],
    servings: 4,
    dietaryTags: ['vegetarian', 'vegan', 'halal', 'gluten_free', 'dairy_free'],
    ingredients: [
      { ingredientId: 'lentil_red', quantity: 250, unit: 'g' },
      { ingredientId: 'onion', quantity: 2, unit: 'piece' },
      { ingredientId: 'garlic', quantity: 4, unit: 'clove' },
      { ingredientId: 'ginger', quantity: 15, unit: 'g' },
      { ingredientId: 'berbere', quantity: 2, unit: 'tbsp' },
      { ingredientId: 'vegetable_oil', quantity: 3, unit: 'tbsp' },
    ],
    steps: [
      R(0, 'Cook onions slowly in oil until deeply golden.'),
      R(1, 'Add garlic, ginger, berbere and toast briefly.'),
      R(2, 'Add lentils and water, simmer until creamy.'),
    ],
  }),
  recipe('spaetzle', 'Cheese spätzle', {
    cuisineIds: ['cu_german'],
    originCountryId: 'c_de',
    prepMinutes: 15,
    cookMinutes: 20,
    difficulty: 'medium',
    mealTypes: ['dinner'],
    servings: 4,
    dietaryTags: ['vegetarian'],
    allergens: ['gluten', 'wheat', 'egg', 'dairy'],
    ingredients: [
      { ingredientId: 'flour', quantity: 300, unit: 'g' },
      { ingredientId: 'egg', quantity: 3, unit: 'piece' },
      { ingredientId: 'milk', quantity: 100, unit: 'ml' },
      { ingredientId: 'onion', quantity: 1, unit: 'piece' },
      { ingredientId: 'butter', quantity: 40, unit: 'g' },
      { ingredientId: 'parmesan', quantity: 100, unit: 'g' },
    ],
    steps: [
      R(0, 'Whisk flour, egg, and milk into a thick batter.'),
      R(1, 'Press through a colander into salted boiling water; fish out when they float.'),
      R(2, 'Toss with browned butter, caramelized onions, and grated cheese.'),
    ],
  }),
  recipe('thai_green_curry_veg', 'Thai green vegetable curry', {
    cuisineIds: ['cu_thai'],
    originCountryId: 'c_th',
    prepMinutes: 15,
    cookMinutes: 20,
    difficulty: 'easy',
    mealTypes: ['dinner'],
    servings: 4,
    dietaryTags: ['vegetarian', 'vegan', 'halal', 'gluten_free', 'dairy_free'],
    ingredients: [
      { ingredientId: 'coconut_milk', quantity: 400, unit: 'ml' },
      { ingredientId: 'tofu', quantity: 300, unit: 'g' },
      { ingredientId: 'eggplant', quantity: 1, unit: 'piece' },
      { ingredientId: 'bell_pepper', quantity: 1, unit: 'piece' },
      { ingredientId: 'basil', quantity: 10, unit: 'g' },
      { ingredientId: 'lime', quantity: 1, unit: 'piece' },
    ],
    steps: [
      R(0, 'Simmer coconut milk, add curry paste, cook until fragrant.'),
      R(1, 'Add vegetables and tofu, simmer until tender.'),
      R(2, 'Finish with basil and lime.'),
    ],
  }),
  recipe('bibimbap', 'Vegetable bibimbap', {
    cuisineIds: ['cu_korean'],
    originCountryId: 'c_kr',
    prepMinutes: 20,
    cookMinutes: 20,
    difficulty: 'medium',
    mealTypes: ['dinner'],
    servings: 2,
    dietaryTags: ['vegetarian', 'halal'],
    allergens: ['soy', 'egg', 'sesame'],
    ingredients: [
      { ingredientId: 'rice', quantity: 200, unit: 'g' },
      { ingredientId: 'spinach', quantity: 100, unit: 'g' },
      { ingredientId: 'carrot', quantity: 1, unit: 'piece' },
      { ingredientId: 'mushroom', quantity: 100, unit: 'g' },
      { ingredientId: 'egg', quantity: 2, unit: 'piece' },
      { ingredientId: 'gochujang', quantity: 2, unit: 'tbsp' },
      { ingredientId: 'sesame', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      R(0, 'Cook rice; sauté each vegetable separately with a touch of sesame.'),
      R(1, 'Arrange over rice, top with a fried egg and gochujang.'),
      R(2, 'Mix at the table.'),
    ],
  }),
  recipe('feijoada_light', 'Lighter feijoada', {
    cuisineIds: ['cu_brazilian'],
    originCountryId: 'c_br',
    prepMinutes: 15,
    cookMinutes: 45,
    difficulty: 'easy',
    mealTypes: ['dinner'],
    servings: 4,
    dietaryTags: ['halal', 'dairy_free'],
    ingredients: [
      { ingredientId: 'black_bean', quantity: 400, unit: 'g' },
      { ingredientId: 'beef', quantity: 400, unit: 'g' },
      { ingredientId: 'onion', quantity: 1, unit: 'piece' },
      { ingredientId: 'garlic', quantity: 3, unit: 'clove' },
      { ingredientId: 'bay', quantity: 1, unit: 'piece', optional: true, note: { en: '(optional)' } },
    ],
    steps: [
      R(0, 'Brown beef with onion and garlic.'),
      R(1, 'Add drained black beans and water to cover, simmer 30 minutes.'),
      R(2, 'Season and serve over rice.'),
    ],
  }),
  recipe('greek_salad', 'Greek salad', {
    cuisineIds: ['cu_greek'],
    originCountryId: 'c_gr',
    prepMinutes: 10,
    cookMinutes: 0,
    difficulty: 'easy',
    mealTypes: ['salad', 'lunch', 'side'],
    servings: 2,
    dietaryTags: ['vegetarian', 'halal', 'gluten_free'],
    allergens: ['dairy'],
    ingredients: [
      { ingredientId: 'tomato', quantity: 3, unit: 'piece' },
      { ingredientId: 'bell_pepper', quantity: 1, unit: 'piece' },
      { ingredientId: 'cheese_feta', quantity: 150, unit: 'g' },
      { ingredientId: 'olive_oil', quantity: 3, unit: 'tbsp' },
      { ingredientId: 'lemon', quantity: 1, unit: 'piece' },
      { ingredientId: 'mint', quantity: 10, unit: 'g' },
    ],
    steps: [
      R(0, 'Chop tomatoes and pepper into bold pieces.'),
      R(1, 'Top with feta, dress with olive oil and lemon, finish with herbs.'),
    ],
  }),
  recipe('mast_o_khiar', 'Mast-o-khiar', {
    cuisineIds: ['cu_iranian', 'cu_afghan'],
    originCountryId: 'c_ir',
    prepMinutes: 10,
    cookMinutes: 0,
    difficulty: 'easy',
    mealTypes: ['side', 'appetizer'],
    servings: 4,
    dietaryTags: ['vegetarian', 'halal', 'gluten_free'],
    allergens: ['dairy', 'tree_nut'],
    ingredients: [
      { ingredientId: 'yogurt', quantity: 500, unit: 'g' },
      { ingredientId: 'mint', quantity: 10, unit: 'g' },
      { ingredientId: 'walnut', quantity: 30, unit: 'g' },
      { ingredientId: 'salt', quantity: 0.5, unit: 'tsp' },
    ],
    steps: [
      R(0, 'Stir yogurt with grated cucumber, dried mint, and chopped walnuts.'),
      R(1, 'Chill 15 minutes before serving.'),
    ],
  }),
  recipe('moroccan_chickpea_stew', 'Moroccan chickpea stew', {
    cuisineIds: ['cu_moroccan'],
    originCountryId: 'c_ma',
    prepMinutes: 10,
    cookMinutes: 25,
    difficulty: 'easy',
    mealTypes: ['dinner'],
    servings: 4,
    dietaryTags: ['vegetarian', 'vegan', 'halal', 'dairy_free'],
    allergens: ['gluten', 'wheat'],
    ingredients: [
      { ingredientId: 'chickpea', quantity: 400, unit: 'g' },
      { ingredientId: 'tomato', quantity: 400, unit: 'g' },
      { ingredientId: 'onion', quantity: 1, unit: 'piece' },
      { ingredientId: 'cumin', quantity: 1, unit: 'tsp' },
      { ingredientId: 'coriander_seed', quantity: 1, unit: 'tsp' },
      { ingredientId: 'cinnamon', quantity: 0.5, unit: 'tsp' },
      { ingredientId: 'couscous', quantity: 200, unit: 'g' },
    ],
    steps: [
      R(0, 'Sauté onion and spices; add tomato and simmer.'),
      R(1, 'Add chickpeas and warm through.'),
      R(2, 'Steam couscous and serve alongside.'),
    ],
  }),
];
